### ISSUE TITLE
not working on system light theme

### ISSUE THREAD

**Issue by godalming123-school** [godalming123/japan#1]

**Comment by godalming123** [comment]
fixed here https://github.com/godalming123/importable-css-js/commit/398f7177832f9570aa2dcfde96275360cc9bdad4#diff-1fa4d18a4135b516316ffdd87c3e58154665f020e4a1f2922f8e9c8688db1cdaR15 since we are importing this repo and it has been updated its fixed

**Comment by godalming123** [comment]
fixed
